name: Generate the pmtiles file.

on:
  push:
    branches: [main]

jobs:
  create-pmtiles:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      e
    - name: Get latest regional osm file.
      run: |
        wget https://download.geofabrik.de/europe/liechtenstein-latest.osm.pbf
    - name: Generate pmtiles
      container: ghcr.io/systemed/tilemaker:master
      run: |
        ls -l #for debugging
        tilemaker --input liechtenstein-latest.osm.pbf --output liechtenstein.pmtiles
        mv liechtenstein.pmtiles liechtenstein.pmtiles.gz

