name: Generate the pmtiles file.

on:
  push:
    branches: [main]

jobs:
  create-pmtiles:
    runs-on: ubuntu-latest

    steps:
    - name: Install tilemaker
      run: sudo apt install -y tilemaker

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get latest regional osm file.
      run: |
        wget https://download.geofabrik.de/europe/germany/bayern/unterfranken-latest.osm.pbf

    - name: Generate pmtiles
      run: |
        ls -l #for debugging
        tilemaker --input unterfranken-latest.osm.pbf --output unterfranken.pmtiles
        mv unterfranken.pmtiles unterfranken.pmtiles.gz

