name: Generate the pmtiles file.

on:
  push:
    branches: [main]

jobs:
  create-pmtiles:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/systemed/tilemaker:master

    steps:
    - name: install download tool
      run: apt-get update && apt-get install -y wget
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Get latest regional osm file.
      run: |
        wget https://download.geofabrik.de/europe/liechtenstein-latest.osm.pbf
    - name: Generate pmtiles
      run: |
        ls -l #for debugging
        /usr/src/app/tilemaker --input liechtenstein-latest.osm.pbf --output liechtenstein.pmtiles
        mv liechtenstein.pmtiles liechtenstein.pmtiles.gz

